### ISSUE TITLE
PR view has extra `edit` button for comments, even when user does not have edit permissions

### ISSUE THREAD

**Issue by rlmark** [unisoncomputing/share-ui#33]
In a PR thread, it looks like the project owner might have an extra "edit" button over comments in the thread that are authored by other contributors. 

See this Discord thread for context: 
https://discord.com/channels/862108724948500490/1296216470329757739/1298737862287822870 

When the project owner tests the "edit" button for a comment in the thread, an error is rendered: 
![editButton](https://github.com/user-attachments/assets/077542ed-3c9d-4d98-b45f-0923ac451e43)

With gratitude to [@haruaokii](https://share.unison-lang.org/@haruaokii) for the help testing this!

**Comment by hojberg** [comment]
Disabled this for now, but we should have a conversation about project moderation as a project owner as this was meant to provided tools for that, in a way similar to what GitHub does.

cc @ChrisPenner
